[workspace]
members = [
    "ggml-rwkv-internal",
    "ggml-rwkv",
    "rwkv-rs",
#    "llama-cli",
    "generate-ggml-bindings"
]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
rand = "0.8.5"
